import PageHeader from "@/components/PageHeader";
import StatusBadge from "@/components/StatusBadge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { CheckCircle2, CircleAlert, Clock3, FolderKey, Github, Workflow } from "lucide-react";

export default function Workflows() {
  return <div><PageHeader eyebrow="Execution and release readiness" title="n8n workflow management" description="The current workflow evidence is drawn from the validated temporary Community Edition import and execution path. Persistent deployment remains deliberately isolated until a Docker host is connected." />
    <div className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]"><Card className="border-primary/25 bg-gradient-to-br from-card to-violet-950/25"><CardHeader><div className="flex items-start justify-between"><div className="flex gap-3"><div className="rounded-xl border border-primary/20 bg-primary/10 p-2.5"><Workflow className="h-5 w-5 text-primary" /></div><div><CardTitle>Daily Automation Control Report (Template)</CardTitle><p className="mt-1 font-mono text-xs text-muted-foreground">Workflow ID · 4a6d2b82-2aaf-4642-98d2-6bcc31c52fb2</p></div></div><StatusBadge status="prepared" /></div></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 md:grid-cols-3"><Metric icon={CheckCircle2} label="Last execution" value="success" /><Metric icon={Clock3} label="Execution timestamp" value="2026-08-16 11:56 UTC" /><Metric icon={FolderKey} label="Runtime mode" value="isolated temporary" /></div><div className="rounded-xl border border-border/80 bg-background/40 p-4"><p className="font-mono text-[10px] uppercase tracking-[0.15em] text-muted-foreground">Execution output</p><pre className="mt-3 overflow-x-auto font-mono text-xs leading-6 text-cyan-100">{`reportTimestamp: 2026-08-16T07:56:01.467-04:00\nstatus: needs_connected_service_checks\nsummary: This template is active only after connected service checks.`}</pre></div><div className="rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm leading-6 text-amber-100"><CircleAlert className="mr-2 inline h-4 w-4" />Persistent n8n is blocked until Docker Desktop and a connected Windows deployment folder are available. No production credentials are stored in this temporary execution.</div></CardContent></Card><div className="space-y-4"><Card><CardHeader><CardTitle className="text-sm">Deployment readiness</CardTitle></CardHeader><CardContent className="space-y-3"><Readiness label="Workflow JSON schema" value="validated" status="active" /><Readiness label="CLI import and execution" value="successful" status="active" /><Readiness label="Persistent Docker host" value="not connected" status="blocked" /><Readiness label="Production credentials" value="template only" status="prepared" /></CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Release trail</CardTitle></CardHeader><CardContent className="space-y-3 text-sm text-muted-foreground"><p className="flex items-center gap-2"><Github className="h-4 w-4 text-primary" />Private automation-control-center repository</p><p className="flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-primary" />automation-control-health validated workflow JSON</p></CardContent></Card></div></div></div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof CheckCircle2; label: string; value: string }) { return <div className="rounded-xl border border-border/80 bg-background/35 p-3"><Icon className="h-4 w-4 text-primary" /><p className="mt-3 font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>; }
function Readiness({ label, value, status }: { label: string; value: string; status: "active" | "prepared" | "blocked" }) { return <div className="flex items-center justify-between gap-3 rounded-xl border border-border/80 p-3"><div><p className="text-sm font-semibold">{label}</p><p className="mt-1 text-xs text-muted-foreground">{value}</p></div><StatusBadge status={status} /></div>; }
